### ISSUE TITLE
Bug: Missing hash and version (for Scoop apps)

### ISSUE THREAD

**Issue by RavenMacDaddy** [martinet101/WingetUI#27] opened 2022-05-24 14:11 UTC
![image](https://user-images.githubusercontent.com/67732686/170056888-2a72f45d-c892-421a-81e9-3c6d23be9d1a.png)

![image](https://user-images.githubusercontent.com/67732686/170056345-d2735b18-62d2-4be3-97cc-303610932101.png)

![image](https://user-images.githubusercontent.com/67732686/170056692-615f0b2c-27d0-46a1-9e7e-16d3690118c2.png)

**Comment by martinet101** [comment] 2022-05-25 11:17
Yes, that's definitely a bug

**Comment by martinet101** [comment] 2022-05-27 13:19
I have been looking at this and it looks that it was caused by the [32:1 weird characters you were having in your output. 
So it has been fixed indirectly

**Closed by martinet101** 2022-05-27 13:19 UTC
Labels: bug, ready-to-go
