### ISSUE TITLE
[FEATURE REQUEST] Show blacklist button to edit blacklist

### ISSUE THREAD

**Issue by rp1231** [martinet101/WingetUI#417] opened 2022-11-15 02:26 UTC
## Before submitting the issue

- [x] **I have checked that the requested feature is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that I am running the latest version of WingetUI**
- [x] **I have checked the [FAQ](https://github.com/martinet101/WingetUI#faq) section**

## Is your feature request related to a problem? Please describe.

It's currently not possible to edit the blacklist.
You can't remove one program from the blacklist, you have to reset it completely.

## Describe the solution you'd like

An extra button to show the blacklist where you can remove programs from it would be nice.
<img width="827" alt="Screenshot 2022-11-15 074859" src="https://user-images.githubusercontent.com/47380919/201811289-4244577f-ca1e-4b2f-9904-b20f5de190d9.png">

**Comment by martinet101** [comment] 2022-11-15 08:36
Duplicate of #284

**Closed by martinet101** 2022-11-15 08:36 UTC
Labels: feature-request
