### ISSUE TITLE
Ability to exclude apps PERMANENTLY from update checking

### ISSUE THREAD

**Issue by sitiom** [martinet101/WingetUI#84] opened 2022-07-15 01:59 UTC
There are apps that I would like to exclude when checking for updates. For example, Winget doesn't properly handle multiple version of Python yet:

![image](https://user-images.githubusercontent.com/56180050/179131370-cfe7ba25-19a5-4ec8-83e9-a8690a23d90a.png)

And so, I would like them to add in the exclusions list when checking for updates, or upgrading all packages.

**Comment by martinet101** [comment] 2022-07-15 09:32
Duplicate of #60

**Comment by sitiom** [comment] 2022-07-15 09:50
@martinet101 Seems to be what I'm looking for, except that I'm looking for excluding apps when the "Upgrade all" button is implemented in #83.

**Comment by martinet101** [comment] 2022-07-15 13:53
Oh, you mean like a permanent exclude

**Comment by martinet101** [comment] 2022-09-04 19:15
Done!
![image](https://user-images.githubusercontent.com/53119851/188329872-3de40563-fbe6-4237-81e9-f1e7e12db616.png)

**Closed** 2022-09-04 19:18 UTC
Labels: feature-request, ready-to-go
